// Centralized list of Aurangabad areas (200+)
// Values are canonical English labels used as IDs/values in filters
// Display should be localized with translateEnum(value, language)
export const AURANGABAD_AREAS: string[] = [
  'Aadgaon',
  'Aapatgaon',
  'Aavishkar Colony',
  'Adarsh Colony',
  'Adul',
  'Airport Area',
  'Alok Nagar',
  'Ambar Hills',
  'Ambad road area',
  'Ansar Colony',
  'Apatgaon',
  'Arif Colony',
  'Asiad Colony',
  'Ashok Nagar',
  'Ashok Nagar (Garkheda)',
  'Aurangabad Caves Rd',
  'Aurangpura (Old City)',
  'Auric City Area MIDC',
  'Ayodhya Nagar',
  'Bajaj Nagar',
  'Bajrang Chowk Area',
  'Balaji Nagar',
  'Balapur Shivar',
  'Banewadi',
  'Banjara Colony',
  'Bansilal Nagar',
  'Bassaiye Nagar',
  'Beed Bypass',
  'Begumpura (Old City)',
  'Bhagat Singh Nagar',
  'Bhalgaon',
  'Bhavsingpura',
  'Bhindon',
  'Bidkin',
  'Bidkin Industrial Park (SBIA)',
  'Bidkin Phase II & III',
  'Brick Factory Rd',
  'Buddhi lane area',
  'Cantonment area',
  'Central Busstand Area',
  'Chandane Chowk Area',
  'Chetna Nagar',
  'Chhawani',
  'Chikalthana',
  'Chikalthana MIDC',
  'Chincholi',
  'Chistiya Chowk Area',
  'Chittegaon',
  'Chittegaon Paithan Road',
  'CIDCO Busstand Area',
  'CIDCO N-1',
  'CIDCO N-10',
  'CIDCO N-11',
  'CIDCO N-12',
  'CIDCO N-13',
  'CIDCO N-14',
  'CIDCO N-15',
  'CIDCO N-2',
  'CIDCO N-3',
  'CIDCO N-4',
  'CIDCO N-5',
  'CIDCO N-6',
  'CIDCO N-7',
  'CIDCO N-8',
  'CIDCO N-9',
  'Connaught',
  'Dashmesh Nagar',
  'Daudnagar',
  'Daulatabad',
  'Deogiri Valley',
  'Deolai Parisar',
  'Deva Nagari',
  'Dhule Solapur Highway',
  'Disha Nagari',
  'Dr. BAMUA University Area',
  'Eknath Nagar',
  'Ellora Road',
  'Farola',
  'Fattepur',
  'Gadiya Vihar Area',
  'Gajanan Maharaj Mandir Area',
  'Gajanan Nagar',
  'Gandheli',
  'Gandheli Gaon',
  'Gandhi Nagar',
  'Ganesh Colony',
  'Gangapur Jahangir',
  'Garampani Area',
  'Garkheda Parisar',
  'Gavalipura',
  'Georai Tanda',
  'Ghati Area',
  'Ghanegaon',
  'Gokul Nagar',
  'Golden City',
  'Golwadi',
  'Gulmohar Colony',
  'Gulmandi',
  'Guru Lawns Area',
  'Gurusahani Nagar',
  'Harsul',
  'Harsul Sawangi',
  'High Court Colony',
  'Himayat Bagh',
  'Hirapur',
  'Honaji Nagar',
  'HUDCO',
  'Indira Nagar Garkheda',
  'Itkheda',
  'Jadhav Mandi',
  'Jaffar Gate Area',
  'Jai Bhawani Nagar',
  'Jai Vishwabharti Colony',
  'Jaisingpura',
  'Jalan Nagar',
  'Jalna Rd',
  'Jatwada',
  'Jawahar Nagar',
  'Jayakwadi Rd',
  'Jogeshwari',
  'Jyoti Nagar',
  'Kailash Nagar',
  'Kamalapur',
  'Kamgar Chowk Cidco',
  'Kanchan Park',
  'Kanchanwadi',
  'Karodi',
  'Karmad',
  'Katkat Gate',
  'Khadkeshwar',
  'Khadkeshwar Area',
  'Khinvasara Park',
  'Khokadpura',
  'Khokari',
  'Kiradpura',
  'Kokanwadi Area',
  'Kranti Chowk Area',
  'Kumbhefal',
  'Kumbharwada',
  'Ladgaon',
  'Lasur',
  'Laxmi Nagar (Garkheda)',
  'Maliwada',
  'Maya Nagar',
  'Mayur Park',
  'Mayurban Colony',
  'MGM Colony',
  'Mhada Colony Chikalthana',
  'Mhada Colony Satara',
  'Mhasoba Nagar',
  'Mill Corner Area',
  'Misarwadi',
  'MIT college Area',
  'Mitamita / Mitmita Road',
  'Mondha Naka Area',
  'Moti Karanja',
  'Mukundwadi',
  'Nagar Naka',
  'Nageshwar wadi',
  'Nagsenvan',
  'Naik Nagar',
  'Nakshatra Wadi',
  'Nakshatrawadi',
  'Nandanvan Colony',
  'Naregaon',
  'Nashik Road',
  'Nasir Nagar',
  'Naygaon',
  'New Hanuman Nagar',
  'New Osmanpura',
  'Nilajgaon',
  'Nipani',
  'Nirala Bazar',
  'Nutan Colony',
  'Old Mondha',
  'Padampura',
  'Padegaon (Padegaon Road)',
  'Pahadsing Pura',
  'Paithan Gate',
  'Palshi Shahar',
  'Panchakki Area',
  'Pandharpur Colony',
  'Pannalal Nagar',
  'Peer Bazar',
  'Phulambri',
  'Pimpri Raja',
  'Pisadevi / Pisadevi area',
  'Pratap Nagar',
  'Pundlik Nagar',
  'Pwd colony',
  'Radhaswami Colony',
  'Railway Station Road',
  'Raj Nagar Mukundwadi',
  'Ram Nagar',
  'Ranjangaon',
  'Ravindra Nagar',
  'Rehmaniya Colony',
  'Renuka Puram',
  'Sadat Nagar',
  'Sadashiv Nagar',
  'Saeeda Colony',
  'Samarth Nagar / Samarthnagar',
  'Samta Nagar',
  'Satara Parisar',
  'Satara Tanda',
  'Savangi',
  'Savedi Rd',
  'Savitri Nagar',
  'Savarkar Nagar',
  'Seven Hill Area',
  'Shajapur',
  'Shah Bazar',
  'Shahganj / Shah Gunj',
  'Shahnoormiya Dargah',
  'Shendra MIDC',
  'Shivaji Nagar',
  'Shreya Nagar',
  'Sindon',
  'Sindhi Colony',
  'South Republic City',
  'Sudhakar Nagar',
  'Sundarwadi',
  'Surana Nagar',
  'T.v.center',
  'Tanaji Chowk Area',
  'Thakare Nagar',
  'Tilak Road',
  'Tisgaon',
  'Turkabad Kharadi',
  'Ulkanagari',
  'Usmanpura / Osmanpura',
  'Uttara Nagari',
  'Vedant Nagar',
  'Vidya Nagar',
  'Vijay Nagar / Vijay Nagar Chowk',
  'Wadgaon',
  'Wadgaon kolhati',
  'Waluj MIDC / Waluj Mahanagar',
  'Wankhade Nagar',
  'Zalta',
  'ZP Road',
];
