// Centralized list of Aurangabad areas (49)
// Values are canonical English labels used as IDs/values in filters
// Display should be localized with translateEnum(value, language)
export const AURANGABAD_AREAS: string[] = [
  'Aurangpura',
  'Bajaj Nagar',
  'Bansilal Nagar',
  'Beed Bypass',
  'Begumpura',
  'Bhavsinghpura',
  'Chikalthana',
  'Chishtiya Colony',
  'CIDCO',
  'Dashmesh Nagar',
  'Deolai',
  'Garkheda',
  'Gulmandi',
  'Harsul',
  'Itkheda',
  'Jadhavwadi',
  'Jalna Road',
  'Jawahar Colony',
  'Jyoti Nagar',
  'Kanchanwadi',
  'Khadkeshwar',
  'Kotla Colony',
  'Kranti Chowk',
  'Mayur Park',
  'MGM',
  'Mondha Naka',
  'Mukundwadi',
  'Nakshatrawadi',
  'Naregaon',
  'New Usmanpura',
  'Nirala Bazar',
  'Osmanpura',
  'Padampura',
  'Padegaon',
  'Paithan Road',
  'Pundlik Nagar',
  'Samarth Nagar',
  'Satara Parisar',
  'Seven Hills',
  'Shahgunj',
  'Shahanurwadi',
  'Shendra MIDC',
  'Shreya Nagar',
  'Sillod Road',
  'Station Road',
  'Tilak Nagar',
  'Town Centre',
  'Ulkanagari',
  'Vedant Nagar',
  'Waluj',
];
