import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'english' | 'marathi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  english: {
    // Personal Information
    'personal_info': 'Personal Information',
    'full_name': 'Full Name',
    'contact_number': 'Contact Number',
    'email_address': 'Email Address',
    
    // Property Type
    'property_type': 'Property Type',
    'residential': 'Residential',
    'commercial': 'Commercial',
    'agricultural': 'Agricultural',
    'industrial': 'Industrial',
    'flat_apartment': 'Flat / Apartment',
    'house_bungalow': 'House/Bungalow',
    'villa': 'Villa',
    'plot_land': 'Plot / Land',
    'office_space': 'Office Space',
    'shop_showroom': 'Shop/Showroom',
    'warehouse': 'Warehouse',
    'building': 'Building',
    'farmland': 'Farmland',
    'orchard': 'Orchard',
    'plantation': 'Plantation',
    'factory': 'Factory',
    'manufacturing_unit': 'Manufacturing Unit',
    'industrial_plot': 'Industrial Plot',
    // Additional Residential Property Types
    'row_house': 'Row House',
    'townhouse': 'Townhouse',
    'bungalow': 'Bungalow',
    'penthouse': 'Penthouse',
    'studio_apartment': 'Studio Apartment',
    'farmhouse': 'Farmhouse',
    'condominium': 'Condominium (Condo)',
    'duplex_triplex': 'Duplex / Triplex',
    'mansion': 'Mansion',
    'cottage': 'Cottage',
    'serviced_apartment': 'Serviced Apartment',
    'garden_flat': 'Garden Flat',
    'loft_apartment': 'Loft Apartment',
    'holiday_home': 'Holiday Home',
    // Additional Commercial Property Types
    'shop_retail': 'Shop / Retail Store',
    'warehouse_godown': 'Warehouse / Godown',
    'hotel_motel': 'Hotel / Motel',
    'restaurant_cafe': 'Restaurant / Café',
    'shopping_mall': 'Shopping Mall / Plaza',
    'clinic_hospital': 'Clinic / Hospital',
    'coworking_space': 'Co-working Space',
    'industrial_shed': 'Industrial Shed / Factory',
    'commercial_land': 'Commercial Land / Plot',
    'it_park': 'IT Park / Business Center',
    'school_college': 'School / College',
    'cinema_multiplex': 'Cinema / Multiplex',
    'banquet_hall': 'Banquet Hall',
    'petrol_pump': 'Petrol Pump',
    'bank': 'Bank',
    'gymnasium': 'Gymnasium / Fitness Center',
    'cold_storage': 'Cold Storage',
    'resort': 'Resort',
    
    // Property Purpose
    'property_purpose': 'Property Purpose',
    'for_sale': 'For Sale',
    'for_rent': 'For Rent',
    'for_lease': 'For Lease',
    
    // Property Details
    'property_details': 'Property Details',
    'area_size': 'Area/Size',
    'carpet_area': 'Carpet Area',
    'built_up_area': 'Built-up Area',
    'super_built_up': 'Super Built-up',
    'plot_area': 'Plot Area',
    'location_address': 'Location/Address',
    'city': 'City',
    'area_locality': 'Area/Locality',
    'pin_code': 'Pin Code',
    'price': 'Price',
    'age_property': 'Age of Property',
    'new_construction': 'New Construction',
    '1_5_years': '1-5 Years',
    '5_10_years': '5-10 Years',
    '10_plus_years': '10+ Years',
    
    // Property Features
    'property_features': 'Property Features',
    'bedrooms': 'Bedrooms',
    'bathrooms': 'Bathrooms',
    '1_bathroom': '1 Bathroom',
    '2_bathrooms': '2 Bathrooms',
    '3_plus_bathrooms': '3+ Bathrooms',
    'parking': 'Parking',
    'car_parking': 'Car Parking',
    'bike_parking': 'Bike Parking',
    'no_parking': 'No Parking',
    'furnishing': 'Furnishing',
    'furnished': 'Furnished',
    'semi_furnished': 'Semi-Furnished',
    'unfurnished': 'Unfurnished',
    'floor': 'Floor',
    'ground_floor': 'Ground Floor',
    '1st_floor': '1st Floor',
    '2nd_floor': '2nd Floor',
    '3rd_plus_floor': '3rd+ Floor',
    
    // Amenities
    'amenities': 'Amenities',
    'lift': 'Lift',
    'swimming_pool': 'Swimming Pool',
    'gym': 'Gym',
    'garden': 'Garden',
    'security': 'Security',
    'power_backup': 'Power Backup',
    'water_supply': 'Water Supply',
    
    // Documentation
    'documentation': 'Documentation',
    'clear_title': 'Clear Title',
    'under_construction': 'Under Construction',
    'legal_issues': 'Legal Issues',
    
    // Additional Information
    'additional_info': 'Additional Information',
    'owner_details': 'Owner Details',
    'property_photos': 'Property Photos',
    'additional_notes': 'Additional Notes',
    'preferred_contact_time': 'Preferred Contact Time',
    'morning': 'Morning',
    'afternoon': 'Afternoon',
    'evening': 'Evening',
    'anytime': 'Anytime',
    
    // Form Actions
    'submit_form': 'Submit Form',
    'get_verified': 'Get Verified',
    'next': 'Next',
    'previous': 'Previous',
    'cancel': 'Cancel',
    'save': 'Save',
    'required_field': 'Required Field',
    'select_option': 'Select an option',
    'upload_option': 'Upload Option',
    'multiple_selection_possible': 'Multiple Selection Possible',
    
    // Verification
    'property_verification': 'Property Verification',
    'verification_form': 'Verification Form',
    'step': 'Step',
    'of': 'of',
    'complete_verification': 'Complete Verification to Get Verified Badge',
    'verification_success': 'Verification submitted successfully! Your property will be reviewed.',
    'verification_error': 'Error submitting verification. Please try again.',
    
    // Property Status
    'verified_property': 'Verified Property',
    'unverified': 'Unverified',
    'pending_verification': 'Pending Verification',
    'verified': 'Verified',
    'rejected': 'Rejected',

    // Hero Section - Modern
    'find_your_perfect': 'Find Your Perfect',
    'property_in': ' Property in',
    'discover_premium_real_estate': 'Discover premium real estate with our AI-powered search platform',
    'property_type_label': 'Property Type',
    'category_label': 'Category',
    'bhk_label': 'BHK',
    'location_label': 'Location',
    'all_locations': 'All Locations',
    'all_types': 'All Types',
    'any': 'Any',
    'not_applicable': 'N/A',
    'buy': 'Buy',
    'rent': 'Rent',
    'lease': 'Lease',
    'apartment': 'Apartment',
    'house': 'House',
    'land': 'Land',
    '1_bhk': '1 BHK',
    '2_bhk': '2 BHK',
    '3_bhk': '3 BHK',
    '4_bhk': '4 BHK',
    '5_bhk': '5+ BHK',
    'select_area_on_map': 'Select Area on Map',
    'click_on_grid_squares': 'Click on grid squares to select locations',
    'search_properties': 'Search Properties',
    'post_free_property_ad': 'Post Free Property Ad',
    'verified_properties': 'verified properties',

    // Services Section - Modern
    'premium_services': 'Premium Services',
    'experience_the_future': 'Experience the future of real estate with our cutting-edge technology and personalized service',
    'smart_property_search': 'Smart Property Search',
    'ai_powered_search': 'AI-powered search to find your perfect property match',
    'property_valuation': 'Property Valuation',
    'get_accurate_market': 'Get accurate market valuations for any property',
    'market_analytics': 'Market Analytics',
    'real_time_insights': 'Real-time insights and market trend analysis',
    'verified_listings': 'Verified Listings',
    'all_properties_verified': 'All properties are thoroughly verified and authenticated',
    'location_intelligence': 'Location Intelligence',
    'detailed_area_insights': 'Detailed area insights and neighborhood analysis',
    'expert_consultation': 'Expert Consultation',
    'connect_with_verified': 'Connect with verified real estate professionals',
    'all_services_included': '✨ All services included in your premium experience',

    // Market Intelligence - Modern
    'ai_powered_research': 'AI-Powered Research',
    'market_intelligence': 'Market Intelligence',
    'advanced_analytics': 'Advanced analytics and machine learning algorithms provide deep insights into Aurangabad\'s real estate market',
    'ai_price_prediction': 'AI Price Prediction',
    'advanced_algorithms': 'Advanced algorithms analyze 50+ market factors',
    'accuracy_percent': '94.2% accuracy',
    'real_time_analytics': 'Real-time Analytics',
    'live_data_from': 'Live data from 15,000+ property transactions',
    'updated_hourly': 'Updated hourly',
    'market_trends': 'Market Trends',
    'deep_insights_emerging': 'Deep insights into emerging neighborhoods',
    'trending_areas': '12 trending areas',
    'investment_score': 'Investment Score',
    'proprietary_scoring': 'Proprietary scoring based on growth potential',
    'roi_up_to': 'ROI up to 18%',
    'research_dashboard': 'Research Dashboard',
    'real_time_market_analysis': 'Real-time market analysis powered by AI algorithms',
    'analysis_type': 'Analysis Type',
    'live_analytics': 'Live Analytics',
    'last_updated': 'Last updated',
    'market_analysis_text': 'Market Analysis',
    'avg_price': 'Avg. Price',
    'price_change': 'Price Change',
    'high_demand': 'High Demand',
    'medium_demand': 'Medium Demand',
    'low_demand': 'Low Demand',
    'view_full_research_report': 'View Full Research Report',

    // Navigation
    'home': 'Home',
    'about': 'About',
    'services': 'Services',

    // Header - Modern
    'list_new_property': 'List New Property',
    'post_property': 'Post Property',
    'login': 'Login',
    'go_to_dashboard': 'Go to Dashboard',
    'login_sign_up': 'Login / Sign Up',
    'sign_out': 'Sign Out',
    'verified_user': 'Verified User',

    // Featured Properties - Modern  
    'featured_properties': 'Featured Properties',
    'view_details': 'View Details',
    'view_all_properties': 'View All Properties',

    // Featured (dotted keys used in components)
    'featured.title': 'Featured Properties',
    'featured.subtitle': 'Discover our handpicked collection of premium properties',
    'featured.viewAll': 'View All Properties',
    'featured.loadingTitle': 'Loading Featured Properties',
    'featured.loadingSubtitle': 'Please wait while we fetch the latest listings',

    // Property common (dotted)
    'property.viewDetails': 'View Details',
    'property.noImage': 'No image available',

    // Search Page
    'search_page.title': 'Find Your Perfect Property',
    'search_page.description': 'Use our advanced search to discover properties that match your needs',

    // Properties Page
    'properties_page.title': 'Browse Properties',
    'properties_page.description': 'Find your perfect property with our smart search',

    // Property Details Page
    'back': 'Back',
    'contact_details': 'Contact Details',
    'call_now': 'Call Now',
    'whatsapp': 'WhatsApp',
    'saved': 'Saved',
    'share': 'Share',
    'quick_details': 'Quick Details',
    'listed_by': 'Listed By',
    'view_on_map': 'View on Map',
    'property_id': 'Property ID',
    'about_property': 'About This Property',
    'amenities_features': 'Amenities & Features',
    'utilities_infrastructure': 'Utilities & Infrastructure',
    'legal_documentation': 'Legal & Documentation',
    'investment_financial_details': 'Investment & Financial Details',
    'connectivity_accessibility': 'Connectivity & Accessibility',
    'security_safety': 'Security & Safety',
    'property_highlights': 'Property Highlights',
    'water_connection': 'Water Connection',
    'electricity_load': 'Electricity Load',
    'sewerage_connection': 'Sewerage Connection',
    'available': 'Available',
    'not_available': 'Not Available',
    'broadband_ready': 'Broadband Ready',
    'title_deed_clear': 'Title Deed Clear',
    'yes': 'Yes',
    'no': 'No',
    'survey_number': 'Survey Number',
    'khata_number': 'Khata Number',
    'revenue_records': 'Revenue Records',
    'approvals_obtained': 'Approvals Obtained',
    'ready_to_move': 'Ready to Move',
    'possession_timeline': 'Possession Timeline',
    'investment_potential': 'Investment Potential',
    'appreciation_forecast': 'Appreciation Forecast',
    'km_to_public_transport': 'km to Public Transport',
    'km_to_airport': 'km to Airport',
    'metro_connectivity': 'Metro Connectivity',
    'cctv_surveillance': 'CCTV Surveillance',
    'earthquake_resistant': 'Earthquake Resistant',
    'security_features': 'Security Features',
    'fire_safety_features': 'Fire Safety Features',
    'built_year': 'Built Year',
    'property_age': 'Property Age',
    'facing': 'Facing',
    'floor_label': 'Floor',
    'bathrooms_label': 'Bathrooms',
    'parking_type': 'Parking Type',
    'parking_spaces': 'Parking Spaces',
    'transaction_type_label': 'Transaction Type',
    'property_category_label': 'Property Category',
    'locality': 'Locality',
    'pincode': 'Pincode',
    'construction_status': 'Construction Status',
    'possession_status': 'Possession Status',
    'property_condition': 'Property Condition',
    'ownership_type': 'Ownership Type',
    'commercial_details': 'Commercial Details',
    'cabins': 'Cabins',
    'conference_rooms': 'Conference Rooms',

    // Footer
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.contactUs': 'Contact Us',
    'footer.careers': 'Careers',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.properties': 'Properties',
    'footer.buyProperties': 'Buy Properties',
    'footer.rentProperties': 'Rent Properties',
    'footer.commercial': 'Commercial',
    'footer.plotsLand': 'Plots/Land',
    'footer.allProperties': 'All Properties',
    'footer.services': 'Services',
    'footer.homeLoans': 'Home Loans',
    'footer.propertyValuation': 'Property Valuation',
    'footer.legalServices': 'Legal Services',
    'footer.interiorDesign': 'Interior Design',
    'footer.propertyManagement': 'Property Management',
    'footer.popularAreas': 'Popular Areas',
    'footer.description': 'Find the best properties in Aurangabad — smart search and expert guidance',
    'footer.rights': '© PropertyShodh — All rights reserved',
    'footer.sitemap': 'Sitemap',

    // SEO
    'seo.home.title': 'PropertyShodh — Aurangabad Real Estate',
    'seo.home.description': 'Find the best properties in Aurangabad with AI search and market insights',
    'seo.search.title': 'Search Properties — PropertyShodh',
    'seo.search.description': 'Discover properties matching your needs with advanced filters and AI-powered tools',
    'seo.properties.title': 'Browse Properties — PropertyShodh',
    'seo.properties.description': 'Explore verified listings across Aurangabad with prices, areas and amenities',
    'seo.property.title': 'Property Details — PropertyShodh',
    'seo.property.description': 'See photos, price, location and contact details for this property'
  },
  marathi: {
    // Personal Information
    'personal_info': 'व्यक्तिगत माहिती',
    'full_name': 'पूर्ण नाव',
    'contact_number': 'संपर्क क्रमांक',
    'email_address': 'ईमेल पत्ता',
    
    // Property Type
    'property_type': 'प्रॉपर्टी प्रकार',
    'residential': 'निवासी',
    'commercial': 'व्यावसायिक',
    'agricultural': 'कृषी',
    'industrial': 'औद्योगिक',
    'flat_apartment': 'फ्लॅट / अपार्टमेंट',
    'house_bungalow': 'घर/बंगला',
    'villa': 'व्हिला',
    'plot_land': 'प्लॉट / जमीन',
    'office_space': 'कार्यालय जागा',
    'shop_showroom': 'दुकान/शोरूम',
    'warehouse': 'गोदाम',
    'building': 'इमारत',
    'farmland': 'शेतजमीन',
    'orchard': 'बाग',
    'plantation': 'लागवड',
    'factory': 'कारखाना',
    'manufacturing_unit': 'उत्पादन युनिट',
    'industrial_plot': 'औद्योगिक प्लॉट',
    // Additional Residential Property Types
    'row_house': 'रो हाऊस',
    'townhouse': 'टाउनहाऊस',
    'bungalow': 'बंगला',
    'penthouse': 'पेंटहाऊस',
    'studio_apartment': 'स्टूडिओ अपार्टमेंट',
    'farmhouse': 'फार्महाऊस',
    'condominium': 'कॉन्डोमिनियम',
    'duplex_triplex': 'डुप्लेक्स / ट्रिप्लेक्स',
    'mansion': 'हवेली',
    'cottage': 'कॉटेज',
    'serviced_apartment': 'सर्विस्ड अपार्टमेंट',
    'garden_flat': 'गार्डन फ्लॅट',
    'loft_apartment': 'लॉफ्ट अपार्टमेंट',
    'holiday_home': 'हॉलिडे होम',
    // Additional Commercial Property Types
    'shop_retail': 'दुकान / रिटेल स्टोअर',
    'warehouse_godown': 'गोदाम',
    'hotel_motel': 'हॉटेल / मोटेल',
    'restaurant_cafe': 'रेस्टॉरंट / कॅफे',
    'shopping_mall': 'शॉपिंग मॉल / प्लाझा',
    'clinic_hospital': 'क्लिनिक / रुग्णालय',
    'coworking_space': 'को-वर्किंग स्पेस',
    'industrial_shed': 'औद्योगिक शेड / कारखाना',
    'commercial_land': 'व्यावसायिक जमीन / प्लॉट',
    'it_park': 'आयटी पार्क / बिझनेस सेंटर',
    'school_college': 'शाळा / कॉलेज',
    'cinema_multiplex': 'सिनेमा / मल्टिप्लेक्स',
    'banquet_hall': 'बॅंक्वेट हॉल',
    'petrol_pump': 'पेट्रोल पंप',
    'bank': 'बॅंक',
    'gymnasium': 'व्यायामशाळा / फिटनेस सेंटर',
    'cold_storage': 'कोल्ड स्टोरेज',
    'resort': 'रिसॉर्ट',
    
    // Property Purpose
    'property_purpose': 'प्रॉपर्टी उद्देश',
    'for_sale': 'विक्रीसाठी',
    'for_rent': 'भाड्याने',
    'for_lease': 'पट्ट्याने',
    
    // Property Details
    'property_details': 'प्रॉपर्टी तपशील',
    'area_size': 'क्षेत्रफळ/आकार',
    'carpet_area': 'कार्पेट एरिया',
    'built_up_area': 'बिल्ट-अप एरिया',
    'super_built_up': 'सुपर बिल्ट-अप',
    'plot_area': 'प्लॉट एरिया',
    'location_address': 'स्थान/पत्ता',
    'city': 'शहर',
    'area_locality': 'परिसर/भाग',
    'pin_code': 'पिन कोड',
    'price': 'किंमत',
    'age_property': 'प्रॉपर्टी वय',
    'new_construction': 'नवीन बांधकाम',
    '1_5_years': '१-५ वर्षे',
    '5_10_years': '५-१० वर्षे',
    '10_plus_years': '१०+ वर्षे',
    
    // Property Features
    'property_features': 'प्रॉपर्टी वैशिष्ट्ये',
    'bedrooms': 'शयनकक्ष',
    'bathrooms': 'स्नानगृह',
    '1_bathroom': '१ स्नानगृह',
    '2_bathrooms': '२ स्नानगृह',
    '3_plus_bathrooms': '३+ स्नानगृह',
    'parking': 'पार्किंग',
    'car_parking': 'कार पार्किंग',
    'bike_parking': 'बाईक पार्किंग',
    'no_parking': 'पार्किंग नाही',
    'furnishing': 'सुसज्जता',
    'furnished': 'सुसज्ज',
    'semi_furnished': 'अर्ध-सुसज्ज',
    'unfurnished': 'असुसज्ज',
    'floor': 'मजला',
    'ground_floor': 'भूतल',
    '1st_floor': 'पहिला मजला',
    '2nd_floor': 'दुसरा मजला',
    '3rd_plus_floor': 'तिसरा+ मजला',
    
    // Amenities
    'amenities': 'सुविधा',
    'lift': 'लिफ्ट',
    'swimming_pool': 'जलतरण तलाव',
    'gym': 'व्यायामशाला',
    'garden': 'बाग',
    'security': 'सुरक्षा',
    'power_backup': 'वीज बॅकअप',
    'water_supply': 'पाणी पुरवठा',
    
    // Documentation
    'documentation': 'कागदपत्रे',
    'clear_title': 'स्पष्ट मालकी',
    'under_construction': 'बांधकाम सुरू',
    'legal_issues': 'कायदेशीर समस्या',
    
    // Additional Information
    'additional_info': 'अतिरिक्त माहिती',
    'owner_details': 'मालकाचे तपशील',
    'property_photos': 'प्रॉपर्टी फोटो',
    'additional_notes': 'अतिरिक्त टिप्पणी',
    'preferred_contact_time': 'संपर्काची योग्य वेळ',
    'morning': 'सकाळ',
    'afternoon': 'दुपार',
    'evening': 'संध्याकाळ',
    'anytime': 'कधीही',
    
    // Form Actions
    'submit_form': 'फॉर्म सबमिट करा',
    'get_verified': 'प्रमाणित करा',
    'next': 'पुढील',
    'previous': 'मागील',
    'cancel': 'रद्द करा',
    'save': 'जतन करा',
    'required_field': 'आवश्यक फील्ड',
    'select_option': 'पर्याय निवडा',
    'upload_option': 'अपलोड पर्याय',
    'multiple_selection_possible': 'अनेक निवड शक्य',
    
    // Verification
    'property_verification': 'प्रॉपर्टी प्रमाणीकरण',
    'verification_form': 'प्रमाणीकरण फॉर्म',
    'step': 'चरण',
    'of': 'चा',
    'complete_verification': 'प्रमाणित बॅज मिळवण्यासाठी प्रमाणीकरण पूर्ण करा',
    'verification_success': 'प्रमाणीकरण यशस्वीरित्या सबमिट केले! तुमच्या प्रॉपर्टीचे पुनरावलोकन केले जाईल.',
    'verification_error': 'प्रमाणीकरण सबमिट करताना त्रुटी. कृपया पुन्हा प्रयत्न करा.',
    
    // Property Status
    'verified_property': 'प्रमाणित प्रॉपर्टी',
    'unverified': 'अप्रमाणित',
    'pending_verification': 'प्रमाणीकरण प्रलंबित',
    'verified': 'प्रमाणित',
    'rejected': 'नाकारले',

    // Hero Section - Modern
    'find_your_perfect': 'तुमची परिपूर्ण',
    'property_in': ' मालमत्ता शोधा',
    'discover_premium_real_estate': 'आमच्या AI-powered शोध प्लॅटफॉर्मसह प्रीमियम रिअल इस्टेट शोधा',
    'property_type_label': 'मालमत्तेचा प्रकार',
    'category_label': 'श्रेणी',
    'bhk_label': 'BHK',
    'location_label': 'स्थान',
    'all_locations': 'सर्व ठिकाणे',
    'all_types': 'सर्व प्रकार',
    'any': 'कोणतेही',
    'not_applicable': 'लागू नाही',
    'buy': 'खरेदी',
    'rent': 'भाडे',
    'lease': 'लीज',
    'apartment': 'अपार्टमेंट',
    'house': 'घर',
    'land': 'जमीन',
    '1_bhk': '१ BHK',
    '2_bhk': '२ BHK',
    '3_bhk': '३ BHK',
    '4_bhk': '४ BHK',
    '5_bhk': '५+ BHK',
    'select_area_on_map': 'नकाशावर क्षेत्र निवडा',
    'click_on_grid_squares': 'स्थाने निवडण्यासाठी ग्रिड चौकांवर क्लिक करा',
    'search_properties': 'मालमत्ता शोधा',
    'post_free_property_ad': 'मोफत मालमत्ता जाहिरात पोस्ट करा',
    'verified_properties': 'सत्यापित मालमत्ता',

    // Services Section - Modern
    'premium_services': 'प्रीमियम सेवा',
    'experience_the_future': 'आमच्या अत्याधुनिक तंत्रज्ञान आणि व्यक्तिगत सेवेसह रिअल इस्टेटचे भविष्य अनुभवा',
    'smart_property_search': 'स्मार्ट मालमत्ता शोध',
    'ai_powered_search': 'तुमच्या परिपूर्ण मालमत्तेशी जुळवून घेण्यासाठी AI-powered शोध',
    'property_valuation': 'मालमत्ता मूल्यांकन',
    'get_accurate_market': 'कोणत्याही मालमत्तेसाठी अचूक बाजार मूल्यांकन मिळवा',
    'market_analytics': 'बाजार विश्लेषण',
    'real_time_insights': 'रिअल-टाइम अंतर्दृष्टी आणि बाजार ट्रेंड विश्लेषण',
    'verified_listings': 'सत्यापित यादी',
    'all_properties_verified': 'सर्व मालमत्ता पूर्णपणे सत्यापित आणि प्रमाणित आहेत',
    'location_intelligence': 'स्थान बुद्धिमत्ता',
    'detailed_area_insights': 'तपशीलवार क्षेत्र अंतर्दृष्टी आणि परिसर विश्लेषण',
    'expert_consultation': 'तज्ञ सल्ला',
    'connect_with_verified': 'सत्यापित रिअल इस्टेट व्यावसायिकांशी जुडा',
    'all_services_included': '✨ तुमच्या प्रीमियम अनुभवामध्ये सर्व सेवा समाविष्ट आहेत',

    // Market Intelligence - Modern
    'ai_powered_research': 'AI-Powered संशोधन',
    'market_intelligence': 'बाजार बुद्धिमत्ता',
    'advanced_analytics': 'प्रगत विश्लेषण आणि मशिन लर्निंग अल्गोरिदम औरंगाबादच्या रिअल इस्टेट मार्केटमध्ये खोल अंतर्दृष्टी प्रदान करतात',
    'ai_price_prediction': 'AI किंमत अंदाज',
    'advanced_algorithms': 'प्रगत अल्गोरिदम ५०+ बाजार घटकांचे विश्लेषण करतात',
    'accuracy_percent': '९४.२% अचूकता',
    'real_time_analytics': 'रिअल-टाइम विश्लेषण',
    'live_data_from': '१५,००० + मालमत्ता व्यवहारांमधील लाइव्ह डेटा',
    'updated_hourly': 'तासाभराने अपडेट',
    'market_trends': 'बाजार ट्रेंड',
    'deep_insights_emerging': 'उदयोन्मुख परिसरांमध्ये खोल अंतर्दृष्टी',
    'trending_areas': '१२ ट्रेंडिंग क्षेत्रे',
    'investment_score': 'गुंतवणूक स्कोअर',
    'proprietary_scoring': 'वाढीच्या संभाव्यतेवर आधारित मालकी स्कोअरिंग',
    'roi_up_to': 'ROI १८% पर्यंत',
    'research_dashboard': 'संशोधन डॅशबोर्ड',
    'real_time_market_analysis': 'AI अल्गोरिदमद्वारे चालवलेले रिअल-टाइम बाजार विश्लेषण',
    'analysis_type': 'विश्लेषण प्रकार',
    'live_analytics': 'लाइव्ह विश्लेषण',
    'last_updated': 'शेवटचे अपडेट',
    'market_analysis_text': 'बाजार विश्लेषण',
    'avg_price': 'सरासरी किंमत',
    'price_change': 'किंमत बदल',
    'high_demand': 'उच्च मागणी',
    'medium_demand': 'मध्यम मागणी',
    'low_demand': 'कमी मागणी',
    'view_full_research_report': 'संपूर्ण संशोधन अहवाल पहा',

    // Navigation
    'home': 'होम',
    'about': 'आमच्याबद्दल',
    'services': 'सेवा',

    // Header - Modern
    'list_new_property': 'नवीन मालमत्ता सूचीबद्ध करा',
    'post_property': 'मालमत्ता पोस्ट करा',
    'login': 'लॉगिन',
    'go_to_dashboard': 'डॅशबोर्डवर जा',
    'login_sign_up': 'लॉगिन / साइन अप',
    'sign_out': 'साइन आउट',
    'verified_user': 'सत्यापित वापरकर्ता',

    // Featured Properties - Modern  
    'featured_properties': 'वैशिष्ट्यीकृत मालमत्ता',
    'view_details': 'तपशील पहा',
    'view_all_properties': 'सर्व मालमत्ता पहा',

    // Featured (dotted keys used in components)
    'featured.title': 'फीचर्ड प्रॉपर्टीज',
    'featured.subtitle': 'काळजीपूर्वक निवडलेल्या प्रीमियम प्रॉपर्टीजचा संग्रह',
    'featured.viewAll': 'सर्व प्रॉपर्टीज पहा',
    'featured.loadingTitle': 'फीचर्ड प्रॉपर्टीज लोड होत आहेत',
    'featured.loadingSubtitle': 'कृपया थांबा, नवीन सूची आणत आहोत',

    // Property common (dotted)
    'property.viewDetails': 'तपशील पहा',
    'property.noImage': 'प्रतिमा उपलब्ध नाही',

    // Search Page
    'search_page.title': 'तुमची परिपूर्ण मालमत्ता शोधा',
    'search_page.description': 'आपल्या गरजांशी जुळणाऱ्या मालमत्ता शोधण्यासाठी आमचा प्रगत शोध वापरा',

    // Properties Page
    'properties_page.title': 'मालमत्ता ब्राउझ करा',
    'properties_page.description': 'आमच्या स्मार्ट शोधासह तुमची परिपूर्ण मालमत्ता शोधा',

    // Property Details Page
    'back': 'मागे',
    'contact_details': 'संपर्क तपशील',
    'call_now': 'आता कॉल करा',
    'whatsapp': 'व्हॉट्सअ‍ॅप',
    'saved': 'जतन केले',
    'share': 'शेअर करा',
    'quick_details': 'त्वरित तपशील',
    'listed_by': 'यांनी सूचीबद्ध',
    'view_on_map': 'नकाशावर पहा',
    'property_id': 'मालमत्ता आयडी',
    'about_property': 'या मालमत्तेबद्दल',
    'amenities_features': 'सुविधा व वैशिष्ट्ये',
    'utilities_infrastructure': 'सुविधा व पायाभूत सुविधा',
    'legal_documentation': 'कायदेशीर व कागदपत्रे',
    'investment_financial_details': 'गुंतवणूक व आर्थिक तपशील',
    'connectivity_accessibility': 'कनेक्टिव्हिटी व प्रवेशयोग्यता',
    'security_safety': 'सुरक्षा व सुरक्षितता',
    'property_highlights': 'ठळक वैशिष्ट्ये',
    'water_connection': 'पाणी कनेक्शन',
    'electricity_load': 'वीज लोड',
    'sewerage_connection': 'जलनिस्सारण कनेक्शन',
    'available': 'उपलब्ध',
    'not_available': 'उपलब्ध नाही',
    'broadband_ready': 'ब्रॉडबँड तयार',
    'title_deed_clear': 'हक्कपत्र स्पष्ट',
    'yes': 'होय',
    'no': 'नाही',
    'survey_number': 'सर्व्हे नंबर',
    'khata_number': 'खाता नंबर',
    'revenue_records': 'रेवेन्यू रेकॉर्ड',
    'approvals_obtained': 'मिळालेली मंजुरी',
    'ready_to_move': 'ताबडतोब राहण्यास तयार',
    'possession_timeline': 'ताबा वेळापत्रक',
    'investment_potential': 'गुंतवणुकीची शक्यता',
    'appreciation_forecast': 'मूल्यवर्धन अंदाज',
    'km_to_public_transport': 'कि.मी. सार्वजनिक वाहतूक',
    'km_to_airport': 'कि.मी. विमानतळ',
    'metro_connectivity': 'मेट्रो कनेक्टिव्हिटी',
    'cctv_surveillance': 'CCTV देखरेख',
    'earthquake_resistant': 'भूकंप प्रतिरोधक',
    'security_features': 'सुरक्षा वैशिष्ट्ये',
    'fire_safety_features': 'अग्निसुरक्षा वैशिष्ट्ये',
    'built_year': 'बांधकाम वर्ष',
    'property_age': 'मालमत्तेचे वय',
    'facing': 'दिशा',
    'floor_label': 'मजला',
    'bathrooms_label': 'स्नानगृह',
    'parking_type': 'पार्किंग प्रकार',
    'parking_spaces': 'पार्किंग जागा',
    'transaction_type_label': 'व्यवहार प्रकार',
    'property_category_label': 'मालमत्ता प्रकार',
    'locality': 'परिसर',
    'pincode': 'पिनकोड',
    'construction_status': 'बांधकाम स्थिती',
    'possession_status': 'ताबा स्थिती',
    'property_condition': 'मालमत्तेची स्थिती',
    'ownership_type': 'मालकी प्रकार',
    'commercial_details': 'व्यावसायिक तपशील',
    'cabins': 'केबिन्स',
    'conference_rooms': 'परिषद कक्ष',

    // Footer
    'footer.company': 'कंपनी',
    'footer.aboutUs': 'आमच्याबद्दल',
    'footer.contactUs': 'संपर्क करा',
    'footer.careers': 'करिअर्स',
    'footer.privacyPolicy': 'गोपनीयता धोरण',
    'footer.termsOfService': 'सेवा अटी',
    'footer.properties': 'प्रॉपर्टीज',
    'footer.buyProperties': 'खरेदीसाठी प्रॉपर्टीज',
    'footer.rentProperties': 'भाड्याने प्रॉपर्टीज',
    'footer.commercial': 'व्यावसायिक',
    'footer.plotsLand': 'प्लॉट/जमीन',
    'footer.allProperties': 'सर्व प्रॉपर्टीज',
    'footer.services': 'सेवा',
    'footer.homeLoans': 'होम लोन्स',
    'footer.propertyValuation': 'प्रॉपर्टी मूल्यांकन',
    'footer.legalServices': 'कायदेशीर सेवा',
    'footer.interiorDesign': 'इंटिरियर डिझाइन',
    'footer.propertyManagement': 'प्रॉपर्टी व्यवस्थापन',
    'footer.popularAreas': 'लोकप्रिय क्षेत्रे',
    'footer.description': 'औरंगाबादमधील सर्वोत्तम प्रॉपर्टीज — स्मार्ट शोध आणि तज्ञ मार्गदर्शन',
    'footer.rights': '© PropertyShodh — सर्व हक्क राखीव',
    'footer.sitemap': 'साइटमॅप',

    // SEO
    'seo.home.title': 'प्रॉपर्टीशोध — औरंगाबाद रिअल इस्टेट',
    'seo.home.description': 'AI शोध आणि बाजार अंतर्दृष्टीसह औरंगाबादमधील सर्वोत्तम मालमत्ता शोधा',
    'seo.search.title': 'मालमत्ता शोधा — प्रॉपर्टीशोध',
    'seo.search.description': 'प्रगत फिल्टर्स आणि AI साधनांसह तुमच्या गरजांशी जुळणाऱ्या मालमत्ता शोधा',
    'seo.properties.title': 'मालमत्ता ब्राउझ करा — प्रॉपर्टीशोध',
    'seo.properties.description': 'किंमती, क्षेत्रफळ आणि सुविधांसह औरंगाबादमधील सत्यापित यादी पाहा',
    'seo.property.title': 'मालमत्ता तपशील — प्रॉपर्टीशोध',
    'seo.property.description': 'या मालमत्तेचे फोटो, किंमत, स्थान आणि संपर्क तपशील पहा'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'english';
  });

  const setLanguageWithPersistence = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage: setLanguageWithPersistence,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};