"use client";

import React, { createContext, useContext, useState, ReactNode, useCallback } from 'react';

type Language = 'en' | 'mr'; // English and Marathi

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string; // Translation function
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Dummy translation data for demonstration
const translations: Record<Language, Record<string, string>> = {
  en: {
    "Find Your Dream Property": "Find Your Dream Property",
    "Explore thousands of listings, from cozy homes to commercial spaces.": "Explore thousands of listings, from cozy homes to commercial spaces.",
    "property_type": "Property Type",
    "property_category": "Property Category",
    "bhk": "BHK",
    "all_locations": "All Locations",
    "select_location": "Select Location",
    "no_location_found": "No location found.",
    "search_locations": "Search locations...",
    "search_by_keyword": "Search by keyword...",
    "Search": "Search",
    "residential": "Residential",
    "commercial": "Commercial",
    "land": "Land",
    "industrial": "Industrial",
    "apartment": "Apartment",
    "house": "House",
    "villa": "Villa",
    "plot": "Plot",
    "office": "Office",
    "shop": "Shop",
    "showroom": "Showroom",
    "warehouse": "Warehouse",
    "agricultural": "Agricultural",
    "residential_plot": "Residential Plot",
    "commercial_plot": "Commercial Plot",
    "factory": "Factory",
    "shed": "Shed",
    "industrial_plot": "Industrial Plot",
    "Any BHK": "Any BHK",
    "Featured Properties": "Featured Properties",
    "Market Insights": "Market Insights",
    "Local Market Data": "Local Market Data",
    "What Our Clients Say": "What Our Clients Say",
    "Finding my dream home was a breeze with this platform. The detailed listings and responsive agents made the process so smooth!": "Finding my dream home was a breeze with this platform. The detailed listings and responsive agents made the process so smooth!",
    "First-time Home Buyer": "First-time Home Buyer",
    "The market insights provided here are invaluable. I've made several profitable investments thanks to their accurate data and expert advice.": "The market insights provided here are invaluable. I've made several profitable investments thanks to their accurate data and expert advice.",
    "Property Investor": "Property Investor",
    "I needed a new office space urgently, and this platform delivered. The filters were precise, and I found the perfect location in no time.": "I needed a new office space urgently, and this platform delivered. The filters were precise, and I found the perfect location in no time.",
    "Commercial Property Seeker": "Commercial Property Seeker",
    "Ready to find your perfect property?": "Ready to find your perfect property?",
    "Contact us today for personalized assistance.": "Contact us today for personalized assistance.",
    "Contact Us": "Contact Us",
    "Home": "Home",
    "Properties": "Properties",
    "About Us": "About Us",
    "Contact": "Contact",
    "Login": "Login",
    "Sign Up": "Sign Up",
    "All Rights Reserved.": "All Rights Reserved.",
    "Privacy Policy": "Privacy Policy",
    "Terms of Service": "Terms of Service",
    "Sitemap": "Sitemap",
    "Quick Links": "Quick Links",
    "Connect With Us": "Connect With Us",
    "Property Title": "Property Title",
    "Location": "Location",
    "Price": "Price",
    "View Details": "View Details",
    "Avg. Price": "Avg. Price",
    "Price Change": "Price Change",
    "Total Properties": "Total Properties",
    "Demand Level": "Demand Level",
    "Trend": "Trend",
    "View More": "View More",
    "Property Showcase": "Property Showcase",
    "Market Data": "Market Data",
    "Testimonials": "Testimonials",
    "Call To Action": "Call To Action",
    "Header": "Header",
    "Footer": "Footer",
    "Modern Hero Section": "Modern Hero Section",
    "Property Type": "Property Type",
    "Property Category": "Property Category",
    "BHK": "BHK",
    "Any BHK": "Any BHK",
    "Search by keyword": "Search by keyword",
    "Search": "Search",
    "all_locations": "All Locations",
    "select_location": "Select Location",
    "no_location_found": "No location found.",
    "search_locations": "Search locations...",
    "property_type": "Property Type",
    "property_category": "Property Category",
    "bhk": "BHK",
    "search_by_keyword": "Search by keyword",
    "Find Your Dream Property": "Find Your Dream Property",
    "Explore thousands of listings, from cozy homes to commercial spaces.": "Explore thousands of listings, from cozy homes to commercial spaces.",
    "Priya Sharma": "Priya Sharma",
    "Rajesh Kumar": "Rajesh Kumar",
    "Anjali Singh": "Anjali Singh",
    "First-time Home Buyer": "First-time Home Buyer",
    "Property Investor": "Property Investor",
    "Commercial Property Seeker": "Commercial Property Seeker",
    "Finding my dream home was a breeze with this platform. The detailed listings and responsive agents made the process so smooth!": "Finding my dream home was a breeze with this platform. The detailed listings and responsive agents made the process so smooth!",
    "The market insights provided here are invaluable. I've made several profitable investments thanks to their accurate data and expert advice.": "The market insights provided here are invaluable. I've made several profitable investments thanks to their accurate data and expert advice.",
    "I needed a new office space urgently, and this platform delivered. The filters were precise, and I found the perfect location in no time.": "I needed a new office space urgently, and this platform delivered. The filters were precise, and I found the perfect location in no time!",
    "Ready to find your perfect property?": "Ready to find your perfect property?",
    "Contact us today for personalized assistance.": "Contact us today for personalized assistance.",
    "Contact Us": "Contact Us",
    "Home": "Home",
    "Properties": "Properties",
    "About Us": "About Us",
    "Contact": "Contact",
    "Login": "Login",
    "Sign Up": "Sign Up",
    "All Rights Reserved.": "All Rights Reserved.",
    "Privacy Policy": "Privacy Policy",
    "Terms of Service": "Terms of Service",
    "Sitemap": "Sitemap",
    "Quick Links": "Quick Links",
    "Connect With Us": "Connect With Us",
    "Featured Properties": "Featured Properties",
    "Market Insights": "Market Insights",
    "Local Market Data": "Local Market Data",
    "What Our Clients Say": "What Our Clients Say",
  },
  mr: {
    "Find Your Dream Property": "तुमची स्वप्नातील मालमत्ता शोधा",
    "Explore thousands of listings, from cozy homes to commercial spaces.": "हजारो सूची एक्सप्लोर करा, आरामदायक घरांपासून ते व्यावसायिक जागांपर्यंत.",
    "property_type": "मालमत्तेचा प्रकार",
    "property_category": "मालमत्ता श्रेणी",
    "bhk": "BHK",
    "all_locations": "सर्व स्थाने",
    "select_location": "स्थान निवडा",
    "no_location_found": "स्थान सापडले नाही.",
    "search_locations": "स्थाने शोधा...",
    "search_by_keyword": "कीवर्डनुसार शोधा...",
    "Search": "शोधा",
    "residential": "निवासी",
    "commercial": "व्यावसायिक",
    "land": "जमीन",
    "industrial": "औद्योगिक",
    "apartment": "अपार्टमेंट",
    "house": "घर",
    "villa": "व्हिला",
    "plot": "प्लॉट",
    "office": "कार्यालय",
    "shop": "दुकान",
    "showroom": "शोरूम",
    "warehouse": "गोदाम",
    "agricultural": "शेती",
    "residential_plot": "निवासी प्लॉट",
    "commercial_plot": "व्यावसायिक प्लॉट",
    "factory": "फॅक्टरी",
    "shed": "शेड",
    "industrial_plot": "औद्योगिक प्लॉट",
    "Any BHK": "कोणतेही BHK",
    "Featured Properties": "वैशिष्ट्यीकृत मालमत्ता",
    "Market Insights": "बाजार अंतर्दृष्टी",
    "Local Market Data": "स्थानिक बाजार डेटा",
    "What Our Clients Say": "आमचे ग्राहक काय म्हणतात",
    "Finding my dream home was a breeze with this platform. The detailed listings and responsive agents made the process so smooth!": "या प्लॅटफॉर्ममुळे माझे स्वप्नातील घर शोधणे खूप सोपे झाले. तपशीलवार सूची आणि प्रतिसाद देणारे एजंट यामुळे प्रक्रिया खूप सुरळीत झाली!",
    "First-time Home Buyer": "प्रथमच घर खरेदीदार",
    "The market insights provided here are invaluable. I've made several profitable investments thanks to their accurate data and expert advice.": "येथे दिलेली बाजारपेठेतील माहिती अमूल्य आहे. त्यांच्या अचूक डेटा आणि तज्ञांच्या सल्ल्यामुळे मी अनेक फायदेशीर गुंतवणूक केली आहे.",
    "Property Investor": "मालमत्ता गुंतवणूकदार",
    "I needed a new office space urgently, and this platform delivered. The filters were precise, and I found the perfect location in no time.": "मला तातडीने नवीन ऑफिसची जागा हवी होती आणि या प्लॅटफॉर्मने ती मिळवून दिली. फिल्टर्स अचूक होते आणि मला लगेच योग्य जागा मिळाली.",
    "Commercial Property Seeker": "व्यावसायिक मालमत्ता शोधक",
    "Ready to find your perfect property?": "तुमची परिपूर्ण मालमत्ता शोधण्यासाठी तयार आहात?",
    "Contact us today for personalized assistance.": "वैयक्तिक मदतीसाठी आजच आमच्याशी संपर्क साधा.",
    "Contact Us": "आमच्याशी संपर्क साधा",
    "Home": "मुख्यपृष्ठ",
    "Properties": "मालमत्ता",
    "About Us": "आमच्याबद्दल",
    "Contact": "संपर्क",
    "Login": "लॉगिन",
    "Sign Up": "नोंदणी करा",
    "All Rights Reserved.": "सर्व हक्क राखीव.",
    "Privacy Policy": "गोपनीयता धोरण",
    "Terms of Service": "सेवा अटी",
    "Sitemap": "साइटमॅप",
    "Quick Links": "जलद दुवे",
    "Connect With Us": "आमच्याशी कनेक्ट व्हा",
    "Property Title": "मालमत्तेचे शीर्षक",
    "Location": "स्थान",
    "Price": "किंमत",
    "View Details": "तपशील पहा",
    "Avg. Price": "सरासरी किंमत",
    "Price Change": "किंमतीतील बदल",
    "Total Properties": "एकूण मालमत्ता",
    "Demand Level": "मागणी पातळी",
    "Trend": "प्रवृत्ती",
    "View More": "अधिक पहा",
    "Property Showcase": "मालमत्ता प्रदर्शन",
    "Market Data": "बाजार डेटा",
    "Testimonials": "प्रशंसापत्रे",
    "Call To Action": "कॉल टू ॲक्शन",
    "Header": "हेडर",
    "Footer": "फूटर",
    "Modern Hero Section": "आधुनिक हिरो विभाग",
    "Property Type": "मालमत्तेचा प्रकार",
    "Property Category": "मालमत्ता श्रेणी",
    "BHK": "BHK",
    "Any BHK": "कोणतेही BHK",
    "Search by keyword": "कीवर्डनुसार शोधा",
    "Search": "शोधा",
    "all_locations": "सर्व स्थाने",
    "select_location": "स्थान निवडा",
    "no_location_found": "स्थान सापडले नाही.",
    "search_locations": "स्थाने शोधा...",
    "property_type": "मालमत्तेचा प्रकार",
    "property_category": "मालमत्ता श्रेणी",
    "bhk": "BHK",
    "search_by_keyword": "कीवर्डनुसार शोधा",
    "Find Your Dream Property": "तुमची स्वप्नातील मालमत्ता शोधा",
    "Explore thousands of listings, from cozy homes to commercial spaces.": "हजारो सूची एक्सप्लोर करा, आरामदायक घरांपासून ते व्यावसायिक जागांपर्यंत.",
    "Priya Sharma": "प्रिया शर्मा",
    "Rajesh Kumar": "राजेश कुमार",
    "Anjali Singh": "अंजली सिंग",
    "First-time Home Buyer": "प्रथमच घर खरेदीदार",
    "Property Investor": "मालमत्ता गुंतवणूकदार",
    "Commercial Property Seeker": "व्यावसायिक मालमत्ता शोधक",
    "Finding my dream home was a breeze with this platform. The detailed listings and responsive agents made the process so smooth!": "या प्लॅटफॉर्ममुळे माझे स्वप्नातील घर शोधणे खूप सोपे झाले. तपशीलवार सूची आणि प्रतिसाद देणारे एजंट यामुळे प्रक्रिया खूप सुरळीत झाली!",
    "The market insights provided here are invaluable. I've made several profitable investments thanks to their accurate data and expert advice.": "येथे दिलेली बाजारपेठेतील माहिती अमूल्य आहे. त्यांच्या अचूक डेटा आणि तज्ञांच्या सल्ल्यामुळे मी अनेक फायदेशीर गुंतवणूक केली आहे.",
    "I needed a new office space urgently, and this platform delivered. The filters were precise, and I found the perfect location in no time.": "मला तातडीने नवीन ऑफिसची जागा हवी होती आणि या प्लॅटफॉर्मने ती मिळवून दिली. फिल्टर्स अचूक होते आणि मला लगेच योग्य जागा मिळाली.",
    "Ready to find your perfect property?": "तुमची परिपूर्ण मालमत्ता शोधण्यासाठी तयार आहात?",
    "Contact us today for personalized assistance.": "वैयक्तिक मदतीसाठी आजच आमच्याशी संपर्क साधा.",
    "Contact Us": "आमच्याशी संपर्क साधा",
    "Home": "मुख्यपृष्ठ",
    "Properties": "मालमत्ता",
    "About Us": "आमच्याबद्दल",
    "Contact": "संपर्क",
    "Login": "लॉगिन",
    "Sign Up": "नोंदणी करा",
    "All Rights Reserved.": "सर्व हक्क राखीव.",
    "Privacy Policy": "गोपनीयता धोरण",
    "Terms of Service": "सेवा अटी",
    "Sitemap": "साइटमॅप",
    "Quick Links": "जलद दुवे",
    "Connect With Us": "आमच्याशी कनेक्ट व्हा",
    "Featured Properties": "वैशिष्ट्यीकृत मालमत्ता",
    "Market Insights": "बाजार अंतर्दृष्टी",
    "Local Market Data": "स्थानिक बाजार डेटा",
    "What Our Clients Say": "आमचे ग्राहक काय म्हणतात",
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en'); // Default language

  const t = useCallback((key: string) => {
    return translations[language][key] || key; // Fallback to key if translation not found
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};