// src/types/database.ts

export interface Property {
  id: string;
  title: string;
  description: string | null;
  property_type: string;
  bhk: number | null;
  price: number;
  location: string;
  city: string;
  carpet_area: number | null;
  amenities: string[] | null;
  possession_status: string | null;
  furnishing_status: string | null;
  parking_spaces: number | null;
  floor_number: number | null;
  total_floors: number | null;
  age_of_property: number | null;
  built_year: number | null;
  facing_direction: string | null;
  images: string[] | null;
  submitted_by_user: boolean | null;
  approval_status: 'pending' | 'approved' | 'rejected';
  listing_status: 'Active' | 'Inactive' | 'Sold' | 'Hidden';
  agent_name: string | null;
  agent_phone: string | null;
  created_at: string;
  updated_at: string;
  google_map_link: string | null;
  verification_status: 'unverified' | 'pending' | 'verified' | 'rejected';
  verification_score: number | null;
  verification_submitted_at: string | null;
  verification_completed_at: string | null;
  user_id: string | null; // UUID of the user who submitted it
  transaction_type: string;
  property_category: string;
  property_subtype: string | null;
  bhk_type: string | null;
  built_up_area: number | null;
  super_built_up_area: number | null;
  plot_area: number | null;
  title_clear: boolean | null;
  under_construction: boolean | null;
  legal_issues: string | null;
  preferred_contact_time: string[] | null;
  language_preference: string | null;
  pincode: string | null;
  locality: string | null;
  ownership_type: string | null;
  maintenance_charges: number | null;
  security_deposit: number | null;
  construction_status: string | null;
  property_condition: string | null;
  water_supply: string | null;
  electricity_backup: string | null;
  bathrooms: number | null;
  parking_type: string | null;
  property_age: string | null;
  owner_details: string | null;
  documentation_status: string | null;
  property_category_detailed: string | null;
  transaction_type_detailed: string | null;
  full_name: string | null;
  email_address: string | null;
  property_purpose: string | null;
  property_subtype_detailed: string | null;
  floor_details: string | null;
  facing_direction_detailed: string | null;
  furnishing_detailed: string | null;
  construction_quality: string | null;
  water_connection: string | null;
  electricity_connection: string | null;
  road_width: number | null;
  corner_property: boolean | null;
  gated_community: boolean | null;
  maintenance_required: boolean | null;
  rental_yield: number | null;
  expected_appreciation: number | null;
  is_featured: boolean;
  featured_at: string | null;
  lift_available: boolean | null;
  society_name: string | null;
  society_maintenance: number | null;
  building_age: number | null;
  floor_plan_type: string | null;
  balconies: number | null;
  view_description: string | null;
  plot_length: number | null;
  plot_width: number | null;
  plot_shape: string | null;
  boundary_wall: boolean | null;
  plot_corner: boolean | null;
  development_permissions: string[] | null;
  zone_classification: string | null;
  office_type: string | null;
  cabin_count: number | null;
  conference_rooms: number | null;
  reception_area: boolean | null;
  it_infrastructure: string[] | null;
  building_grade: string | null;
  front_footage: number | null;
  display_windows: number | null;
  foot_traffic_rating: string | null;
  business_licenses: string[] | null;
  construction_materials: string[] | null;
  construction_grade: string | null;
  structural_warranty: string | null;
  modular_kitchen: boolean | null;
  wardrobes_count: number | null;
  bathroom_fittings: string | null;
  water_connection_type: string | null;
  electricity_load: number | null;
  sewerage_connection: boolean | null;
  broadband_ready: boolean | null;
  backup_power: string | null;
  title_deed_clear: boolean | null;
  approvals_obtained: string[] | null;
  survey_number: string | null;
  khata_number: string | null;
  revenue_records: string | null;
  ready_to_move: boolean | null;
  possession_timeline: string | null;
  investment_potential: string | null;
  appreciation_forecast: string | null;
  soil_type: string | null;
  water_source: string[] | null;
  irrigation_type: string | null;
  crop_history: string[] | null;
  farm_equipment_included: boolean | null;
  public_transport_distance: number | null;
  highway_connectivity: string | null;
  airport_distance: number | null;
  metro_connectivity: string | null;
  security_features: string[] | null;
  cctv_surveillance: boolean | null;
  fire_safety_features: string[] | null;
  earthquake_resistant: boolean | null;
  featured_until: string | null;
}

export interface Lead {
  id: string;
  created_at: string;
  updated_at: string;
  source_type: string;
  source_id: string | null;
  name: string;
  phone: string;
  email: string | null;
  property_id: string | null;
  property_title: string | null;
  city: string | null;
  location: string | null;
  budget_range: string | null;
  property_type: string | null;
  purpose: string | null;
  status: 'new' | 'contacted' | 'qualified' | 'unqualified' | 'closed_won' | 'closed_lost';
  priority: 'low' | 'medium' | 'high';
  tags: string[];
  assigned_admin_id: string | null; // UUID
  next_follow_up_at: string | null;
  last_contacted_at: string | null;
  notes: string | null;
}