export interface Property {
  id: string;
  title: string;
  description?: string | null;
  property_type: string;
  bhk?: number | null;
  price: number;
  location: string;
  city: string;
  carpet_area?: number | null;
  built_up_area?: number | null;
  super_built_up_area?: number | null;
  plot_area?: number | null;
  amenities?: string[] | null;
  possession_status?: string | null;
  listing_status: string;
  contact_number?: string | null;
  google_map_link?: string | null;
  images?: string[] | null;
  furnishing?: string | null;
  highlights?: string[] | null;
  built_year?: number | null;
  floor?: string | null;
  facing?: string | null;
  agent_name?: string | null;
  agent_phone?: string | null;
  submitted_by_user?: boolean;
  approval_status?: string;
  verification_status?: string;
  verification_score?: number | null;
  transaction_type?: string;
  property_category?: string;
  agricultural_land_type?: string | null;
  property_subtype?: string | null;
  bhk_type?: string | null;
  total_floors?: number | null;
  floor_number?: number | null;
  facing_direction?: string | null;
  age_of_property?: number | null;
  parking_spaces?: number | null;
  title_clear?: boolean | null;
  under_construction?: boolean | null;
  legal_issues?: string | null;
  preferred_contact_time?: string[] | null;
  language_preference?: string | null;
  pincode?: string | null;
  locality?: string | null;
  ownership_type?: string | null;
  maintenance_charges?: number | null;
  security_deposit?: number | null;
  construction_status?: string | null;
  property_condition?: string | null;
  water_supply?: string | null;
  electricity_backup?: string | null;
  verification_documentation?: any | null;
  additional_notes?: string | null;
  bathrooms?: number | null;
  parking_type?: string | null;
  property_age?: string | null;
  owner_details?: string | null;
  documentation_status?: string | null;
  property_category_detailed?: string | null;
  transaction_type_detailed?: string | null;
  full_name?: string | null;
  email_address?: string | null;
  property_purpose?: string | null;
  property_subtype_detailed?: string | null;
  floor_details?: string | null;
  facing_direction_detailed?: string | null;
  furnishing_detailed?: string | null;
  construction_quality?: string | null;
  water_connection?: string | null;
  electricity_connection?: string | null;
  road_width?: string | null;
  corner_property?: boolean | null;
  gated_community?: boolean | null;
  maintenance_required?: boolean | null;
  rental_yield?: number | null;
  expected_appreciation?: number | null;
  is_featured?: boolean | null;
  featured_at?: string | null;
  featured_until?: string | null;
  created_at: string;
  updated_at: string;
}

export interface PropertyFormData {
  title: string;
  description?: string;
  property_type: string;
  property_category?: string;
  agricultural_land_type?: string;
  bhk?: number;
  price: number;
  location: string;
  city: string;
  carpet_area?: number;
  amenities?: string[];
  possession_status?: string;
  listing_status: string;
  contact_number?: string;
  google_map_link?: string;
  images?: string[];
  furnishing?: string;
  highlights?: string[];
  built_year?: number;
  floor?: string;
  facing?: string;
  agent_name?: string;
  agent_phone?: string;
}
