-- Add enhanced property details columns based on comprehensive property flow
ALTER TABLE public.properties 
ADD COLUMN built_up_area numeric,
ADD COLUMN super_built_up_area numeric,
ADD COLUMN plot_area numeric,
ADD COLUMN bathrooms integer DEFAULT 1,
ADD COLUMN parking_type text,
ADD COLUMN property_age text,
ADD COLUMN owner_details text,
ADD COLUMN documentation_status text,
ADD COLUMN property_category_detailed text,
ADD COLUMN transaction_type_detailed text DEFAULT 'sale',
ADD COLUMN full_name text,
ADD COLUMN email_address text,
ADD COLUMN preferred_contact_time text[],
ADD COLUMN property_purpose text,
ADD COLUMN property_subtype_detailed text,
ADD COLUMN floor_details text,
ADD COLUMN facing_direction_detailed text,
ADD COLUMN furnishing_detailed text,
ADD COLUMN construction_quality text,
ADD COLUMN water_connection text,
ADD COLUMN electricity_connection text,
ADD COLUMN road_width text,
ADD COLUMN corner_property boolean DEFAULT false,
ADD COLUMN gated_community boolean DEFAULT false,
ADD COLUMN maintenance_required boolean DEFAULT false,
ADD COLUMN rental_yield numeric,
ADD COLUMN expected_appreciation numeric;