-- Add only missing enhanced property details columns
ALTER TABLE public.properties 
ADD COLUMN IF NOT EXISTS plot_area numeric,
ADD COLUMN IF NOT EXISTS bathrooms integer DEFAULT 1,
ADD COLUMN IF NOT EXISTS parking_type text,
ADD COLUMN IF NOT EXISTS property_age text,
ADD COLUMN IF NOT EXISTS owner_details text,
ADD COLUMN IF NOT EXISTS documentation_status text,
ADD COLUMN IF NOT EXISTS property_category_detailed text,
ADD COLUMN IF NOT EXISTS transaction_type_detailed text DEFAULT 'sale',
ADD COLUMN IF NOT EXISTS full_name text,
ADD COLUMN IF NOT EXISTS email_address text,
ADD COLUMN IF NOT EXISTS preferred_contact_time text[],
ADD COLUMN IF NOT EXISTS property_purpose text,
ADD COLUMN IF NOT EXISTS property_subtype_detailed text,
ADD COLUMN IF NOT EXISTS floor_details text,
ADD COLUMN IF NOT EXISTS facing_direction_detailed text,
ADD COLUMN IF NOT EXISTS furnishing_detailed text,
ADD COLUMN IF NOT EXISTS construction_quality text,
ADD COLUMN IF NOT EXISTS water_connection text,
ADD COLUMN IF NOT EXISTS electricity_connection text,
ADD COLUMN IF NOT EXISTS road_width text,
ADD COLUMN IF NOT EXISTS corner_property boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gated_community boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS maintenance_required boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS rental_yield numeric,
ADD COLUMN IF NOT EXISTS expected_appreciation numeric;